"""empty message

Revision ID: ee10fd1e5fbd
Revises: 551260958cbd
Create Date: 2023-12-04 15:22:09.960238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee10fd1e5fbd'
down_revision = '551260958cbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint('user', type_='foreignkey')
        batch_op.drop_column('user')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('user', 'user', ['user'], ['id'])

    # ### end Alembic commands ###
